name: Deployment Workflow

on:
  push:
    branches: [master] # is triggered if push event in master branch occurs

jobs:
  Test and lint:
    runs-on: ubuntu-latest
    steps:
      - name: Reuse Workflow from Template
      uses: ./.github/workflows/development.yaml
   
  Build:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        uses: actions/upload-pages-artifact@v2
 
  Deployment:
    # should run AFTER test and build (see `needs`) 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup github pages 
        uses: actions/configure-pages@v3

      - name: Download the build artifacts
        uses: actions/download-artifact@v3

      - name: Deploy to github pages
        uses: actions/deploy-pages@v2 