name: Development Workflow

on:
  push:
    branches: [development] # is triggered if push event in development branch occurs

jobs:
  test and lint:
    uses: jerreeey/Frontend-Applikation/.github/workflows/testing_and_linting.yaml
